spring:
  config:
    import:
      - "optional:classpath:bot.yaml"
      - "optional:classpath:attribute.yaml"
      - "optional:classpath:dir_info.yaml"

  data:
    redis:
      host: ${SPRING_REDIS_HOST:redis}
      port: ${SPRING_REDIS_PORT:6379}
    redis-channel:
      not-confirmed: not-confirmed
      first-question: first-question
      second-question: second-question

logging:
  level:
    org.springframework: INFO
    ru.pereguzochka.telegram_bot: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%level] %logger{36} - %msg%n"

bot-backend:
  host: http://localhost
  port: 8081
